### ISSUE TITLE
Community referrals

### ISSUE THREAD

**Issue by jecihjoy** [palladiumkenya/kenyaemr-esm-3.x#182]
This feature is in the   `community-referrals`  branch. At the moement this is how it looks like

I can use some helps on the following
1. Add nav bar and a relevant icon
2. Metrics cards for `Community Referrals total` and `Facility Referrals total` - Lanyo
3. Fixing of css, ideally the `pull referrals button` should be on the right
4. On the active tab we should see the current action buttons, but on switching to `completed` tab we should see only one button `View Patient` which should navigate a user to patient chart
5. `View Reasons` button is not displaying data 
6. Breaking tests

I am currently focusing on aligning the rest endpoints

@donaldkibet @makombe @ojwanganto @gabriel090

**Comment by jecihjoy** [comment]
How to run the code

`openmrs develop --sources packages/esm-shr-app  --port 8055 --backend https://dev.kenyahmis.org`

**Comment by Rugute** [comment]
Remove the video it has live client data. NUPI

**Comment by Rugute** [comment]
> This feature is in the `community-referrals` branch. At the moement this is how it looks like
> 
>  Screencast.from.19-03-2024.10.38.14.ASUBUHI.webm 
> I can use some helps on the following
> 
> 1. Add nav bar and a relevant icon - Lanyo
> 2. Metrics cards for `Community Referrals total` and `Facility Referrals total` - Lanyo
> 3. Fixing of css, ideally the `pull referrals button` should be on the right
> 4. On the active tab we should see the current action buttons, but on switching to `completed` tab we should see only one button `View Patient` which should navigate a user to patient chart
> 5. `View Reasons` button is not displaying data
> 6. Breaking tests
> 
> I am currently focusing on aligning the rest endpoints
> 
> @donaldkibet @makombe @ojwanganto @gabriel090

Video has client Identifiers

**Comment by ojwanganto** [comment]
Thanks, @Rugute. Those are test data though

**Comment by ojwanganto** [comment]
@KorirC we can instead just make an element of the row clickable and redirect one to patient chart. It will save you from handling a button. I hope this makes sense

**Comment by donaldkibet** [comment]
Is this issue resolved since work on it is already merged in cc @ojwanganto @Rugute
